export default {
    STREAM: "Stream",
    MAIN_PROGRAM: "MainProgram",
    SUB_PROGRAM: "SubProgram",
    BENEFIT: "Benefit",
    APPROVE: "Approve",
    REJECT: "Reject",
    FILTER_SUB_PROGRAMS_INSIDE_STREAM: "filter_Subprograms_Inside_Stream",
    FILTER_SUB_PROGRAMS_INSIDE_MAINPROGRAM: "filter_Subprograms_Inside_MainProgram",
    FILTER_SUB_PROGRAMS_OUTSIDE: "filter_Subprograms_Outside",
    FILTER_BENEFITS_INSIDE_STREAM: "filter_Benefits_Inside_Stream",
    FILTER_BENEFITS_INSIDE_MAINPROGRAM:"filter_Benefits_Inside_MainProgram",
    FILTER_BENEFITS_INSIDE_SUB_PROGRAM: "filter_Benefits_Inside_Subprogram",
    FILTER_BENEFITS_OUTSIDE: "filter_Benefits_Outside",
    INTEGRATION_FIELD : "Integration",
    INPUT_FIELD : "INPUT",
    CALCULATION_FIELD : "CALCULATION",
    COMPLEX_FIELD :"COMPLEX",
    GROUP_FIELD : "GROUP",
    APPROVE_FIELD_API:"ACCEPT_FIELD",
    SUBMIT_FIELDS_REQUESTS_API:"SUBMIT_FOR_APPROVAL",
    COMPLETE_FIELDS_REQUESTS_API:"COMPLETE",
    EDIT_SIMULATION_MODEL : "Edit_Simulation_Model",
    EXECUTE_SIMULATION_MODEL : "Execute_Simulation_Model",
    VERIFY_FILE_UPLOADED : "verifyFileUploaded",
    API_Input_Source_Input:"ادخال",
    SUBDOMAIN_CHILD_FIELD: "Field",
    SUBDOMAIN_CHILD_DOMAIN:"Domain"

};