export default {
    STREAM: "Stream",
    MAIN_PROGRAM: "MainProgram",
    SUB_PROGRAM: "SubProgram",
    BENEFIT: "Benefit",
    APPROVE: "Approve",
    REJECT: "Reject",
    READY_FOR_EXECUION: "Ready",
    FILTER_SUB_PROGRAMS_INSIDE_STREAM: "filter_Subprograms_Inside_Stream",
    FILTER_SUB_PROGRAMS_INSIDE_MAINPROGRAM: "filter_Subprograms_Inside_MainProgram",
    FILTER_SUB_PROGRAMS_OUTSIDE: "filter_Subprograms_Outside",
    FILTER_BENEFITS_INSIDE_STREAM: "filter_Benefits_Inside_Stream",
    FILTER_BENEFITS_INSIDE_MAINPROGRAM:"filter_Benefits_Inside_MainProgram",
    FILTER_BENEFITS_INSIDE_SUB_PROGRAM: "filter_Benefits_Inside_Subprogram",
    FILTER_BENEFITS_OUTSIDE: "filter_Benefits_Outside",
    INTEGRATION_FIELD : "Integration",
    INPUT_FIELD : "Insert",
    CALCULATION_FIELD : "Calculation",
    COMPLEX_FIELD :"Complex",
    GROUP_FIELD : "Group",
    SUBDOMAIN_CHILD_FIELD: "Field",
    SUBDOMAIN_CHILD_DOMAIN:"Domain"
};